server:
  port: 8082

spring:
  application:
    name: investmentadvise
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-58899864.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaafmiw6ydg96WW35d7
            client-secret: K4MYFnE-VoUGFBy7MZa61Ew1JHPNxk9gUDI5rK43WAGZjDGFNbtnglumuolUs27s

        provider:
          okta:
            issuer-uri: https://dev-58899864.okta.com/oauth2/default


okta:
  oauth2:
    issuer: https://dev-58899864.okta.com/oauth2/default
    audience: api://default

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8078/eureka/

