server:
  port: 8081

spring:
  application:
    name: riskprofile


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8078/eureka/

okta:
  oauth2:
    issuer: https://dev-58899864.okta.com/oauth2/default
    audience: api://default
